version: 2.1
orbs:
  terraform: circleci/terraform@dev:alpha
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
      - terraform/validate:
          checkout: true
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/apply:
          attach-workspace: true
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
